### ISSUE TITLE
mutiple cameras over websocket?

### ISSUE THREAD

**Issue by Classsic** [OliverF/mjpeg-relay#11]
Is possible see more than one cameras/stream over websocket? I want a solution for multiview, and I dont know if I have to use multiple ws o can send multicameras over one ws.
thanks in advance.

**Comment by Silex** [comment]
Only one camera per websocket is possible... multiple cameras over a websocket does not make sense, and would be pretty complicated to implement.

**Comment by OliverF** [comment]
So what you're after is a way to have the feeds of multiple cameras combined into 1 stream? Not currently possible and as Silex said, quite complicated to implement.

If you have multiple cameras and want to display their feeds on a single page, I would start 1 instance of mjpeg-relay for each camera. Then you can embed each stream side by side on a web page - that sounds like what you're after if I interpreted your question correctly :)
