### ISSUE TITLE
Doesn't work with Axis 216 or Sony CH110

### ISSUE THREAD

**Issue by Fohdeesha** [OliverF/mjpeg-relay#12]
Hi, I can't seem to get mjpeg-relay working with my PoE security cams.

it runs the script no problem saying starting new http connection etc,, however when I visit http://localhost:54017/stream it just loads forever, it's a blank page that never actually loads.

Interestingly the status page shows me as a client with outgoing bandwidth, so I'm not sure what's going on.

Same behavior with all the axis 216 series cams I have (some 216FD's and a 216MFD) as well as my sony CH110, providing the standard mjpg URL to the relay of "http://192.168.1.19/mjpg/video.mjpg" and "http://192.168.1.20/mjpeg" for the sony

Going directly to these links without the relay succesfully pulls up an mjpg stream in all my browsers, so I don't know why mjpeg-relay is having an issue with them. Any help is appreciated, I really need this working! I can provide remote access to the system for you to debug if it helps

**Comment by OliverF** [comment]
Hmm that's certainly odd behaviour. Could you please copy/paste the output of mjpeg-relay after a client connects?

Additionally, have you tried streaming in WebSockets mode?

**Comment by Fohdeesha** [comment]
Thanks for the quick reply! Do you mean command line output? There isn't any when a client connects (or rather attempts to connect, its just an infinite loading page). Its just the first couple lines of http connection to the camera and the bounderyset line.

Is there a command flag to get more verbose output? I remember trying websockets a while back and having the same behavior. 

Could it be image size related? Now that I think about it the cams I've tried it with have HD outputs with pretty low compression (large bitrate mjpeg stream)

Willing to do any debugging neseccary to get this working!

**Comment by OliverF** [comment]
No problem, happy to help. Command line output at startup is what I'm after - it sounds like the boundary is not getting picked up fully. What would be great is if you could pick up a sample of the stream directly from your cameras and a sample from mjpeg-relay (as you say, it does appear to show a client has connected). WireShark could help.

The image size is a good point - I've only ever tested with low bitrate streams, so it could be worth keeping in mind. I can't imagine how that would cause a problem, however (aside from high CPU usage). Worth having a look at the memory/CPU usage of mjpeg-relay whilst it's streaming.

I'd take up your offer of remote access but unfortunately I'm away from my PC today.

**Comment by OliverF** [comment]
On second thought we might be OK with just knowing the headers - might be possible to see in Chrome in the Network tab in developer mode. If you could inspect the headers in the response from the camera and a response from mjpeg-relay, we can see if the boundary separator has been correctly picked up by mjpeg-relay. Hope that makes sense!

**Comment by Fohdeesha** [comment]
Thanks again for looking into this! I'm at work until late tonight but when I get home I'll grab all the info you're after including headers. I'll also crank down the bitrate on one camera as low as I can and see if it makes a difference. I remember checking CPU usage and its extremely low, 1 or 2 percent

**Comment by Fohdeesha** [comment]
sorry for the delay on this, it's been a crazy week. Tomorrow I should have time to grab everything. thanks again for the help!

**Comment by Fohdeesha** [comment]
Finally getting some time to get back to this!

This is the output when starting the relay. When I connect via browser, there's no new output, and the browser just indefinitely loads, same for all cameras

```
root@web:~/mjpeg-relay# python relay.py "http://192.168.1.20/mjpeg"
Starting new HTTP connection (1): 192.168.1.20
Connected to stream source, boundary separator: --myboundary
```

**Comment by Fohdeesha** [comment]
I also just tried to view the headers and record the request traffic with chrome's built in inspector as you suggested - I have to say it has a very nice interface and tons of helpful options.

A few times it didn't want to show anything at all in the network activity list like the relay wasn't even responding but after a few refreshes I got it to show up in the inspector. see headers here - http://i.imgur.com/AjsfI00.png

here are the headers when loading the camera stream directly without the relay which works great - http://i.imgur.com/W4zvyE6.png

to make sure it wasn't a browser extension or something I turned them all off and also tried another fresh browser, same result. My offer for remote access still stands, I'm sure you could see something I'm missing!

EDIT: just to make sure it wasn't a bandwidth related thing like we mentioned before, I cranked the cam down to 320x240, maximum compression so the stream was just a few kilobits, and same result. as expected the image from the camera also looked horrible :P

**Comment by Fohdeesha** [comment]
Woah, think I may have found something. I went to double check CPU usage and the relay is pegged at 100%. It's a pretty beefy processor too, a recent Xeon that I run a LOT of heavy duty stuff on and have never seen this kind of usage, especially not from a python script.

here- http://i.imgur.com/wAhb6us.png

That's before I even attempt to connect too, just right after starting it from the command line. I feel like that's a bug? I can't imagine relaying a network stream of a few kilobits would wreck a recent Xeon. I've done actual re-encoding of h264 streams on these processors and saw half the CPU usage

I turned the camera down to 320x240 so the stream was barely 12kbps and the cpu usage started much lower, around 5%, but then slowly grew to 100% pegged like before over the course of about 60 to 90 seconds. Very strange!

**Comment by OliverF** [comment]
Thanks for the information, I think you're on to something there with that slow rise in CPU.

It leads me to believe mjpeg-relay is correctly connecting and streaming from the cameras, but for whatever reason is falling over when streaming to clients.

May I please have a URL for one of your cameras so I can debug on my side?

I'm also going to setup a test MJPEG stream on my own server for you to try relaying from, just to make sure it isn't a problem with your setup.

In the meantime, could you please try your setup in WebSockets mode?

Cheers

**Comment by OliverF** [comment]
Here's a test stream from my server, please give this a go to confirm your setup:
http://mjpeg.bitnode.co.uk:5000/

(right click the image, copy address, paste it as the source address in mjpeg-relay)

**Comment by Fohdeesha** [comment]
Just relayed your test stream and it worked perfectly, on top of that relay.py is using less than a single percent of cpu while doing so. So that's good!

I emailed my cams streaming address to the email you have listed on http://oliverfoyle.co.uk/

it's not a particularly secure camera and exposing the mjpeg stream means exposing it's whole UI so I was a bit paranoid about posting it out in the open :)

edit: just saw your websockets request, i'm headed out of the house for now but tonight I should be able to test that

**Comment by Fohdeesha** [comment]
Any luck reproducing? hoping my remote stream is still working for you!

**Comment by Fohdeesha** [comment]
please halpp

**Comment by Silex** [comment]
@Fohdeesha: can you give #13 a try? It'd fix your problem.

**Comment by Fohdeesha** [comment]
wow, will definitely give this a go tonight! I'm sure Oliver will be happy to see your pull request, he's been quite busy and don't think he's had time to debug this himself

**Comment by OliverF** [comment]
Sorry for seemingly dropping off the face of the Earth - as @Fohdeesha pointed out I've been very busy indeed.

@Silex Thank you very much for your work on this.

**Comment by Fohdeesha** [comment]
just gave this a go and it's now working perfectly! relaying my previous "problem" cameras (axis and sony POE) with zero issue. relaying full HD streams with very little resources (1% cpu use and 1% memory)

thanks so much for this @Silex and @OliverF - I can now finally finish my web project with this stupid sony cam that only supports 1 stream client at a time

**Comment by Silex** [comment]
@Fohdeesha: glad to hear that! :wink:
