### ISSUE TITLE
No basic/digest auth support

### ISSUE THREAD

**Issue by Silex** [OliverF/mjpeg-relay#2]
Hello,

Just so you're aware, I had to modify the source to add in basic auth authorization.

I think the CLI would be better if you just gave it the full url source instead of the `HOST:PORT PATH` separation.

That way one would write:

`python relay.py -p 9000 "http://user:password@10.10.10.204:10020/axis-cgi/mjpg/video.cgi?camera=1&time=1423069038&resolution=1600x1200&compression=40"`

Maybe you could use request (http://docs.python-requests.org/en/latest) instead of raw sockets?

I'll probably make a PR to add at least basic auth support.

**Comment by OliverF** [comment]
Hi there,

Thanks for the feedback. The CLI improvement you mentioned makes much more sense. Some time next week, I'll revisit the CLI and make the change.

The requests library looks good - also appears to support stream responses, so it should work here for streaming from the MJPEG source. I'll spend some time next week experimenting with it.

The next step is to see what you've already done in terms of authorization - if you could please make a PR for it when you're ready, I'll take a look and we'll go from there.

Thanks for your time and effort.

**Comment by Silex** [comment]
Well, at the moment I just hacked the source so it adds a `Authorization: Basic qgAniQgeIOgNIOqeg` field ot the GET request... but this needs proper refactoring.

If you're going to use the request lib, we can simplify it a lot:

``` python
import requests
from contextlib import closing
with closing(requests.get("http://user:password@10.10.10.204:10020/axis-cgi/mjpg/video.cgi", stream = True)) as r:
  print(r.headers['Content-Type'])  # TODO: parse boundary from that
  for chunk in r.iter_content(2048): # TODO: keep chunks and split over boundary
    print("read chunk")
```

Output:

```
multipart/x-mixed-replace; boundary=myboundary
read chunk
read chunk
read chunk
read chunk
read chunk
read chunk
read chunk
read chunk
```

And no need for much support... just pass to url straight to requests.

**Comment by OliverF** [comment]
Understood - makes sense to use requests then.
Thanks for the example - I've got a couple of spare hours tonight, I'll go ahead and implement this. I'll update the CLI at the same time, too.

Cheers.

**Comment by Silex** [comment]
:+1:
