### ISSUE TITLE
Feature Request: Overlay Text

### ISSUE THREAD

**Issue by zoomzoomluke** [OliverF/mjpeg-relay#7]
Hi,

I'm not sure how easy it would be to implement, but it would be pretty cool to have the stats overlaid by specifying the position, size etc.

Much like how motion does with the time / date / text field.

Would this be something that is doable?

Great work by the way, saving my bandwidth!
- Luke

**Comment by Silex** [comment]
What kind of overlay are you talking about? Overlay on the MJPEG stream? Like a JPEG overlay?

**Comment by zoomzoomluke** [comment]
Yes, overlay text onto the MJPEG stream to display for example number of viewers or perhaps custom text?

If you see the current stream at  http://media.aiopi.com:8081/stream http://media.aiopi.com:8081/stream you will already see that motion overlays some text but it would be nice if this could be controlled by mjpeg-relay.

**Comment by Silex** [comment]
In my opinion this is a bad idea... this information is better shared as plain text next to the widget that displays the MJPEG stream. Creating an overlay directly on the JPEGs would also use lots of CPU, I'm not even sure it's feasible with more than 5 frames per seconds.

Anyway, we'll see what @OliverF will say about it.

**Comment by zoomzoomluke** [comment]
No worries. It was just a thought ;)  

I could perhaps generate a separate graphic in mjpeg-relay, i’m sure my python is capable enough to do this based on the existing status information.

Only reason for wanting it integrated was to be able to have the info in a standard <img> tag for example on forums etc.

**Comment by Silex** [comment]
Just display another div on top with the desired information.

**Comment by OliverF** [comment]
Hi Luke,

I've considered this in the past but I believe the low latency of mjpeg-relay is achieved through minimal processing of the stream. As such, I think adding such a feature would increase the latency and, as Silex mentioned, may significantly increase the CPU usage. Perhaps if you were able to demonstrate this feature working without too much of a performance hit then I could incorporate it? If you do implement your own, drop me a message and I'll check it out for sure!

Thanks
