### ISSUE TITLE
Seems to be a problem with python 2.6

### ISSUE THREAD

**Issue by deltaray** [OliverF/mjpeg-relay#8]
First of all thanks for this program, its exactly what I was looking for.

When I try to run the program on a host with python2.6 (CentOS 6 based) I receive the following error:

Traceback (most recent call last):
  File "./relay.py", line 359, in <module>
    broadcast = Broadcaster(args[0], status)
  File "./relay.py", line 182, in **init**
    "{}".format(len(feedLostImage), feedLostImage)
ValueError: zero length field name in format
  dataArray[0] = 0;

Any ideas?  I'm able to run it on python 2.7.

**Comment by OliverF** [comment]
It looks like Python 2.6 doesn't support unnamed positional specifiers in string.format. I've used them all over the place in mjpeg-relay, so your best bet is to just use 2.7 if it works!

**Comment by deltaray** [comment]
Ok that's fine. Thanks for the quick reply and keep up the good work.
